---
- name: Do base configuration
  include_role:
    name: "ten7.flightdeck_base"
- name: Install needed software
  apk:
    name: "{{ _pkgs | join(',') }}"
    state: present
    update_cache: yes
  vars:
    _pkgs:
      - "apache2"
      - "apache2-proxy"
      - "libcap"
      - "zlib"
      - "php83-apache2"
      - "php83"
      - "git"
      - "patch"
      - "curl"
      - "go-task"
      - "php83-bcmath"
      - "php83-ctype"
      - "php83-curl"
      - "php83-dom"
      - "php83-fileinfo"
      - "php83-gd"
      - "php83-iconv"
      - "php83-intl"
      - "php83-ldap"
      - "php83-mbstring"
      - "php83-pecl-memcached"
      - "php83-mysqli"
      - "php83-mysqlnd"
      - "php83-opcache"
      - "php83-openssl"
      - "php83-pecl-apcu"
      - "php83-sqlite3"
      - "php83-pdo"
      - "php83-pdo_mysql"
      - "php83-pdo_sqlite"
      - "php83-phar"
      - "php83-soap"
      - "php83-session"
      - "php83-simplexml"
      - "php83-sodium"
      - "php83-tokenizer"
      - "php83-xdebug"
      - "php83-exif"
      - "php83-xml"
      - "php83-xmlreader"
      - "php83-xmlwriter"
      - "php83-zip"
      - "php83-zlib"
      - "py3-mysqlclient"
      - "composer"
      - "mariadb-client"
      - "rsync"
      - "openssh-client"
  notify:
    - clear caches
- name: Add global php symlink
  file:
    src: "/usr/bin/php83"
    dest: "/usr/local/bin/php"
    state: link
    force: yes
    follow: no
- name: Add global go-task symlink
  file:
    src: "/usr/bin/go-task"
    dest: "/usr/local/bin/task"
    state: link
    force: yes
    follow: no
- name: Force Composer to be ran with PHP 8.3
  lineinfile:
    path: "/usr/bin/composer"
    regexp: '^/usr/bin/php8'
    line: '/usr/bin/php83 /usr/bin/composer.phar $@'
- name: Ensure key directories are owned by the web user
  file:
    path: "{{ item }}"
    state: directory
    owner:  "app"
    group:  "app"
    mode: "u=rwx,g=rwx,o=r"
    recurse: yes
  loop:
    - "/ansible"
    - "/etc/apache2"
    - "/etc/ssl/apache2"
    - "/etc/apache2/sites.d"
    - "/etc/php83"
    - "/run/apache2"
    - "/var/log/apache2"
    - "/var/www"
    - "/srv/html"
- name: Link logs files to stdout for the Docker log collector
  file:
    src: "{{ item }}"
    dest: "/dev/stdout"
    state: link
    force: yes
    follow: no
  loop:
    - "/var/log/apache2/access.log"
    - "/var/log/apache2/000_default-access_log"
    - "/var/log/apache2/000_default_ssl-access_log"
- name: Link logs files to stderr for the Docker log collector
  file:
    src: "{{ item }}"
    dest: "/dev/stderr"
    state: link
    force: yes
    follow: no
  loop:
    - "/var/log/apache2/error.log"
    - "/var/log/apache2/000_default-error_log"
    - "/var/log/apache2/000_default_ssl-error_log"
- name: Template default index.html
  template:
    src: "templates/index.html"
    dest: "/srv/html/index.html"
    owner:  "app"
    group:  "app"
    mode: "u=rw,g=r,o=r"
